### ISSUE TITLE
Table: Transactions

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/harmony_dbt#1]
**Description**
Let's create a Transactions table using `chainwalkers.prod.harmony_txs` as the source data table.

**To Do Next:**

- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [x] Schema build review
- [x] Submit Pull Request

**Comment by mattromano** [comment]
### Proposed Transaction Schema

Going to keep up the theme of the Dune based schema design. Similar to ethereum.transactions with EIP-1559 stuff removed and Harmony addresses added + a few other small changes.

| block_time | txn_id | nonce | txn_index | native_from_address | native_to_address | eth_from_address | eth_to_address | value | block_number | block_hash | gas_price | gas | data |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| 2021-12-08 03:19:12.000 | 0x6ca0455ebc282b8fe06d65d49b40fd14414eb878ded751a7cc22cc55746d463d | 0x98ee9| 72 |one1dkdthqncpeu2vn5e7mstr905tmugt5keap0749 | one1yyjetxcr77ttyczt0xqcuy07tznn0ml0dw45sk | 0x6d9abb82780e78a64e99f6e0b195f45ef885d2d9 | 0x2125959b03f796b2604b79818e11fe58a737efef | 0 | 20217726 | 0xbb38b2fddb1203463eb198676ffffc8bb78e4df304ee7cfdb38f3834cf01024e | 1230100000  | 593623 | 0xe5546f37...|

I was also thinking of maybe bringing in contract address but not sure if that's better suited for other tables. 

CC: @chuxinh let me know your thoughts and if we want to add or remove anything else!

For reference: [Harmony Txn Docs](https://docs.harmony.one/home/developers/api/methods/transaction-related-methods/hmy_gettransactionbyhash ) & [Dune Txn Table](https://docs.dune.xyz/data-tables/data-tables/raw-data/ethereum-data)

**Comment by chuxinh** [comment]
Nice work @mattromano 😄 Have some small feedback below: 
- [x] block_time
- [ ] tx_id (**worth changing to just `hash` or `tx_hash`?** )
- [x] nonce
- [x] tx_index
- [x] native_from_address
- [x] native_to_address
- [x] eth_from_address 
- [x] eth_to_address 
- [x] value
- [x] block_number
- [x] block_hash
- [x] block_number
- [x] gas_price
- [x] gas
- [x] data
- [ ] contract_address (**mostly null but worth bringing in? see below**)
![image](https://user-images.githubusercontent.com/30974572/147615487-484d92b8-6490-427a-befa-50b7499def35.png)
- [ ] status (**also worth bringing this in as true/false**)

seems like the ones with contract address in the field normally don't have `to` and they have internal transaction `create`
example: https://explorer.harmony.one/tx/0x798c446670f932ac06dd75c47cfa1029a6bea96e8220157e11ee4773d637799b?activeTab=0
https://explorer.harmony.one/tx/0x932334dd6630f2eaf8722f93051635b886bb1cb58be9457019285e42f81b1db2https://explorer.harmony.one/tx/0x932334dd6630f2eaf8722f93051635b886bb1cb58be9457019285e42f81b1db2

**Comment by antonyip** [comment]
> Nice work @mattromano 😄 Have some small feedback below:
> 
> * [x]  block_time
> * [ ]  tx_id (**worth changing to just `hash`?** )
> * [x]  nonce
> * [ ]  tx_index (**index?**)
> * [x]  native_from_address
> * [x]  native_to_address
> * [x]  eth_from_address (**or just use from**)
> * [x]  eth_to_address (**to**)
> * [x]  value
> * [x]  block_number
> * [x]  block_hash
> * [x]  block_number
> * [x]  gas_price
> * [x]  gas
> * [x]  data
> * [ ]  contract_address (**mostly null but worth bringing in? see below**)
>   ![image](https://user-images.githubusercontent.com/30974572/147615487-484d92b8-6490-427a-befa-50b7499def35.png)
> * [ ]  status (**also worth bringing this in as true/false**)
> 
> seems like the ones with contract address in the field normally don't have `to` and they have internal transaction `create` example: https://explorer.harmony.one/tx/0x798c446670f932ac06dd75c47cfa1029a6bea96e8220157e11ee4773d637799b?activeTab=0 https://explorer.harmony.one/tx/0x932334dd6630f2eaf8722f93051635b886bb1cb58be9457019285e42f81b1db2https://explorer.harmony.one/tx/0x932334dd6630f2eaf8722f93051635b886bb1cb58be9457019285e42f81b1db2

I’d like to refrain from using from/to as from’s a keyword in sql. from_address / to_address would be my preferred choice. 

I feel hash and index might not feel easily understandable for a newcomer.

**Comment by mattromano** [comment]
Great thanks for the feedback both! Based on the feedback above I think the final Schema should look something like this:

- [x] block_time
- [ ] tx_id (**worth changing to just `hash` or `tx_hash`?** ) **_--moved to `hash` and in similar order to Dune txn table_**
- [x] nonce
- [x] index
- [x] native_from_address
- [x] native_to_address
- [x] from_address 
- [x] to_address 
- [x] value
- [x] block_number
- [x] block_hash
- [x] gas_price
- [x] gas
- [x] hash (**_can provide documentation to help newcomer understand, but want to keep naming convention as close to Dune as possible so it is familiar to on-chain analysts_**)
- [x] data
- [ ] contract_address **_(will exclude as most are internal create transactions or NULL, maybe we can include later?)_**
- [x] status **_(when 0x0 FALSE, when 0x1 TRUE)_**

Going to start working on the PR for this table, let me know if there are any other changes you think we should include.
