### ISSUE TITLE
[Documentation] Using netlify to generate documentation

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#103]
https://discourse.getdbt.com/t/publishing-dbt-docs-to-netlify/121

**Comment by D0R11** [comment]
Hello, taking this issue. Created an account and did the steps indicated in the link you've provided. Deploying the docs as we speak.

**Comment by antonyip** [comment]
Cool. Let me know how it goes.

**Comment by D0R11** [comment]
https://wondrous-maamoul-10f823.netlify.app/#!/overview

Works well as intended. Are we going to add a domain for this or is this good?

**Comment by antonyip** [comment]
- is it possible to hand over control to me or its just static?
- will have to talk to mdao people for the domain..
- what are the steps required for me to update the page?

**Comment by D0R11** [comment]
@antonyip Sorry I just got back now, pretty busy schedule.

The site I sent was just static so I'll remove it for now. 

We can proceed with continuous development by linking this repository to Netlify and then creating a `netlify.toml` file wherein it is indicated there which subdirectory will only be deployed to Netlify. With continuous development, the website will update with the latest commit.

**Comment by D0R11** [comment]
I forgot to add, 

the command `dbt docs generate` will be the command in place so that it will be run everytime a commit has been pushed to master.

reference: https://answers.netlify.com/t/support-guide-what-if-my-project-folder-is-not-the-root-of-my-git-repository/123

**Comment by D0R11** [comment]
@antonyip sent a request to link harmony_dbt as a git repo in Netlify for issue 103

![image](https://user-images.githubusercontent.com/99073366/166423412-3080b445-eada-48c3-9158-fdc29fe4e03a.png)

**Comment by antonyip** [comment]
> @antonyip sent a request to link harmony_dbt as a git repo in Netlify for issue 103
> 
> ![image](https://user-images.githubusercontent.com/99073366/166423412-3080b445-eada-48c3-9158-fdc29fe4e03a.png)

@drakedanner could you handle this? I’m not mdao admin so can’t follow up.

**Comment by D0R11** [comment]
Hello, any updates on this? @drakedanner 

Thanks!
