### ISSUE TITLE
Upgrade: dbt docker image

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#12]
I see a new version of dbt docker image that has been release by the dbt team. 
<https://hub.docker.com/layers/fishtownanalytics/dbt/1.0.0/images/sha256-4c9462867d2db6869a048ba429d3557a562ac20337d4ce25b634c0e026954028?context=explore>
Probably a simple change in tagging on the DOCKERFILE but it needs to be tested.

**Comment by drakedanner** [comment]
Can we get some more details here?

**Comment by antonyip** [comment]
![image](https://user-images.githubusercontent.com/9086733/171744373-66651cda-d899-4ba2-a8d4-93df7c1986a1.png)
