### ISSUE TITLE
[Table] ERC1155 Mints and Burns

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#121]
Look for TransferSingle Event (topic0: `0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62` )
Calculate daily mints and burns of each token.
This will be from '0x000...000' or to '0x000...000'
`TransferSingle(address,address,address,uint256,uint256)`

**Comment by Albert-Debbarma** [comment]
i would love to solve this issue ?can you please what exactly need to be done?
