### ISSUE TITLE
Table: HRC20 Tokens

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#13]
... Since i'm on this page. Might as well write my thoughts down... @drakedanner feel free to refactor the whole ticket.

| token_address | token_decimals | token_symbol | token_name |
| --- | --- | --- | --- |
0x.. | 18 | WONE | Wrapped ONE |

<https://github.com/antonyip/harmony_dbt/blob/experiments/models/playground/ant_tokens2.sql>

**To Do Next:**

- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [x] Schema build review
- [x] Submit Pull Request

**Comment by drakedanner** [comment]
This looks great @antonyip 

Push it forward and look to @chuxinh or @forgxyz for review
