### ISSUE TITLE
ONE token price incorrect

### ISSUE THREAD

**Issue by lizmartinis** [MetricsDAO/harmony_dbt#135]
mdao_harmony.tokenprice_one is not showing the ONE token price correctly. Seems to be showing Jewel price instead. 

Issue submitted to flipside by Sam - discord community moderator.

**Comment by eevui** [comment]
Where _do_ we collect information about token prices? I do see the tables, but where do they come from?

**Comment by antonyip** [comment]
Think its based off dex prices. With the hack of harmony bridge. Stable coins aren’t keeping the peg anymore.

**Comment by eevui** [comment]
Ah you're right.

Checking the model, it is indeed basin off JEWEL price. There's a `tokenprices` table that contains a `WONE` mapping. So we can base it off there, no?
