### ISSUE TITLE
Table: Blocks

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/harmony_dbt#2]
**Description**
Let's create a Blocks table using `chainwalkers.prod.harmony_blocks` as the source data table.

**To Do Next:**

- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [x] Schema build review
- [x] Submit Pull Request

**Comment by chuxinh** [comment]
Proposed schema (similar to `ethereum.blocks`):
| block_id | block_timestamp         | block_hash                                                         | block_parent_hash                                                  | gas_limit | gas_used | miner                                      | nonce             | size  | tx_count |
|----------|-------------------------|--------------------------------------------------------------------|--------------------------------------------------------------------|-----------|----------|--------------------------------------------|--------------------|-------|----------|
| 20411945 | 2021-12-12 21:40:59.000 | 0x769c8bbdaea5e997ba086c88c6e9d8cd0be95b01348023088db5896fc8d33563 | 0xad645a816098f31de9aa95ace41ecf665ec025318f85783c4bdf2f2c0958d49b | 80000000  | 18103273 | 0x45df588b05a675b5f16e253aa15d90333df9fedf | 0x0000000000000000 | 23223 | 34       |

There are some other block properties that might be useful but I'm not too sure:
- [x] extra_data
- [x] logs_bloom
- [x] mix_hash
- [ ] receipts_root
- [ ] state_root
- [x] transactions (probably not in this case as we will have separate transaction table)
- [x] transactions_root (probably not in this case as we will have separate transaction table)
- [x] uncles

cc: @forgxyz let me know if it looks fine to you! 
reference: https://docs.harmony.one/home/developers/api/methods/transaction-related-methods/hmy_getblockbyhash#returns-1

**Comment by drakedanner** [comment]
Note that the `ethereum.blocks` is from the Dune database

**Comment by forgxyz** [comment]
I agree with the schema you've proposed. 
Sample data we are working with only goes to 12/8/2021 so this may need to be reevaluated on a larger data set, but the following can be left out of our schema as there is only one distinct / common result
- extra_data
- mix_hash
- uncles

logs_bloom - as we are creating a logs table, we can disregard this. Explanation of what this is used for by EVM found [here](https://ethereum.stackexchange.com/questions/3418/how-does-ethereum-make-use-of-bloom-filters/3426).

Agree that transaction data is going to be in a separate table.

Finally,
receipts_root and state_root - we could consider adding these to the table as [tries](https://medium.com/@eiki1212/ethereum-state-trie-architecture-explained-a30237009d4e) are an integral part of EVM. Interestingly, these are not unique to each block, if you run:

`select  
    distinct header:state_root,  
    count(1)  
from chainwalkers.prod.harmony_blocks  
group by 1  
order by 2 desc `

**Comment by drakedanner** [comment]
Split the .yml into a per table .yml then should be good
