### ISSUE TITLE
Remove and rename duplicated models

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/harmony_dbt#27]
![image](https://user-images.githubusercontent.com/11461756/149640937-c11d763b-015a-44dc-b816-1bb1b4ac3478.png)

We have duplicate models in production, some with a dedupe call out. 

Let's make sure they are properly de-duplicated and name them without the prefix of deduped

Feel free to add comments here and/or find me on discord to discuss danner.eth#7297

**Comment by antonyip** [comment]
blocks_deduped/txs_deduped is a copy of the data from chainwalkers with the duplicates removed, maybe you'd like to rename it to something else?

**Comment by antonyip** [comment]
TODO: remove blocks_deduped / txs_deduped from production tables

**Comment by antonyip** [comment]
Dropped blocked_deduped and txs_deduped from production tables.
