### ISSUE TITLE
Table: Logs

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/harmony_dbt#3]
Let's create a Transactions table using `chainwalkers.prod.harmony_txs` as the source data table.

**Two things to note:**
1. Data should be extracted from `tx:receipt:logs`. Logs has a decoded attribute that is dynamic per the contract log emitted. This should be a JSON variant column in the logs table we produce.
2. You will need to use [Snowflake's lateral flatten](https://docs.snowflake.com/en/sql-reference/functions/flatten.html) functionality to expand the tx.reciept.logs into individual rows.  

**To Do Next:**

- [x] Design the schema for this table
- [x] Get confirmation on schema
- [x] Build schema
- [x] Schema build review
- [x] Submit Pull Request

**Comment by forgxyz** [comment]
Proposed Schema:
| block_id | block_timestamp | tx_hash | event_index | native_contract_address | evm_contract_address | contract_name | event_name | event_inputs | topics | data |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| 20262093 | 2021-12-09 05:08:23.000 | 0x55afe68bb7b137978693d8402b027a8259c9b8793d79e95b47d0972ee4ec5dd4 | 0x0 | one1ta6nmn0ekxke427px3npf505w3hadnjuhlh7vv | 0x5f753dcdf9b1ad9aabc1346614d1f4746fd6ce5c | "" | "" | null | ["0x7be34da84992130f23438d167b22f7f7a246aaaf2d7e9dd3c988ee1672fe40fc",...] | "0x000000000000000000000000000000000000000000000000..." |


 - [ ] removed = true on zero transactions in dataset, thoughts on including anyway?
 - [ ] purposely excluding information such as block_hash as that can be cross referenced via block_id with core.blocks

**Comment by antonyip** [comment]
1. evm_address -> contract_address? (because the column beside it is contract_name). could be evm_address + evm_name too... but I think our chainwalker is not able to extract the name of the contract for now...
2. tx_id -> I guess it'll be up to discussion based on what's decided on (tx_id / tx_hash / tx_eth_hash).

**Comment by forgxyz** [comment]
Yes, it's the contact address, but so is native_address. So maybe native_contract_address and evm_contract_address.  
  
Agree, I will be consistent with other tables depending on what we decide, and change tx_id if need-be.

**Comment by forgxyz** [comment]
Initial logs model up, please review both the sql and structure of the table to ensure it is what we want to build on.

Reference for column descriptions: https://docs.harmony.one/home/developers/api/methods/filter-methods/hmy_getlogs

**Comment by drakedanner** [comment]
https://github.com/MetricsDAO/harmony_dbt/tree/add-logs

**Comment by forgxyz** [comment]
Table successfully built by dbt using truncated dedupe_tx macro. I'd like to factor out this macro as two planned core tables are dependent on a deduped transactions table, and it doesn't make sense to duplicate that compute. Holding PR until we can discuss.


## Testing
```
dbt test --models test_logs_macro

20:35:35  Found 4 models, 14 tests, 0 snapshots, 0 analyses, 182 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics
20:35:36  Concurrency: 4 threads (target='default')
20:35:39  Finished running 11 tests in 3.36s.
20:35:39  Completed successfully
20:35:39  Done. PASS=11 WARN=0 ERROR=0 SKIP=0 TOTAL=11
```


  
logs.yml was updated to remove not_null test constraints from:
- event_name
- contract_name
- inputs

On inspection of sample data (150k rows), 44 records returned NULL values for these columns. There is a rare instance where logs:decoded is null, thus these values will be null.
