### ISSUE TITLE
Table: Transfers

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/harmony_dbt#4]
Let's create a Transfers table to highlight which assets are moving between two parties. This can be created using `chainwalkers.prod.harmony_txs` as the source data table.

This table should extract `ONE` transfers and all transfers from decoded logs.

Hints:
- You should be able to determine if this is a `ONE` transfer if there is a value set at the tx level. 
- Also, always check the decoded logs for a `Transfer` event name.

**To Do Next:**

- [ ] Design the schema for this table
- [ ] Get confirmation on schema
- [ ] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request

**Comment by drakedanner** [comment]
Starting point from Flipside's Terra Transfers model 
![image](https://user-images.githubusercontent.com/11461756/148306453-6b9d1207-3e59-42d6-bc99-7cfc5a6c406b.png)

**Comment by ndhung1104** [comment]
Proposed Schema:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Hp/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Hp/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">

<div style='box-sizing: border-box;display:inline-block;background-image:linear-gradient(rgb(255, 255, 255), rgb(239, 239, 239));
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;widows: 2;
-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;text-decoration-style: initial;
text-decoration-color: initial'>



BLOCK_ID | BLOCK_TIMESTAMP | TX_ID | FROM_ADDRESS | TO_ADDRESS | CONTRACT_ADDRESS | RAW_AMOUNT
-- | -- | -- | -- | -- | -- | --
21081746 | 2021-12-29   11:06:08.000 | 0x50b71a3b68dc690a3daa4176146572b32c1fd338d6a73d676e954780b7f94f54 | 0x25836011bbc0d5b6db96b20361a474cbc5245b45 | 0xd325970ab2c4efabdaf1b4dea350506f7d38433c | 0xcf664087a5bb0237a0bad6742852ec6c8d69a27a | 1.33E+16



</body>

</html>

Sample table can be found under harmony.dev.transfers.

Sample table code: (the txs and logs table will be replaced with the logs table of forgxyz afterward)
```sql
{{ config(
  materialized='incremental', 
  unique_key= "CONCAT_WS('-', 'block_id', 'tx_id', coalesce('chain_id',-1), coalesce('from_address',''), coalesce('to_address',''), coalesce('contract_address',''))",
  incremental_strategy = 'delete+insert',
  cluster_by = ['block_timestamp'],
  tags=['core_ndhung1104']
) }}

with txs as (
  select 
    q.tx_id, 
    q.block_id, 
    q.block_timestamp, 
    q.chain_id,
    q.tx:receipt:logs as logs_raw
  from 
    {{ deduped_txs("harmony_txs") }} q
  where 
    {{ incremental_load_filter("block_timestamp") }}
),
logs as (
  select 
    txs.tx_id, 
    txs.block_id, 
    txs.block_timestamp, 
    txs.chain_id,
    value:address::string as address, 
    value:decoded:eventName::string as eventName, 
    value:decoded:inputs as inputs 
  from 
    txs, lateral flatten (input => logs_raw) 
),
transfers as (
  select
    block_id,
    tx_id,
    block_timestamp,
    chain_id,
    address as contract_address,
    inputs:from::string as from_address,
    inputs:to::string as to_address,
    inputs:value::float as raw_amount
  from 
    logs
  where 
    eventName = 'Transfer'
) 
select 
  *
from 
  transfers
```

**Comment by antonyip** [comment]
![image](https://user-images.githubusercontent.com/9086733/149043208-563a70d3-1d06-426d-b6f2-2e749c333931.png)
I see some null values, might wanna consider coalesce(value:decoded:inputs,0) as inputs

tx_id is 0x563deb1b9409f0ccac996a0ef52240f5307ad61fe0771e5713a0d8805cc9dc47
tx from blockchain is 
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0x0ada348ac4423b5158398cabc13cc729437d7e4e077dd50cd3c6a4c2f4789ae9",
        "blockNumber": 21081746,
        "ethHash": "0x563deb1b9409f0ccac996a0ef52240f5307ad61fe0771e5713a0d8805cc9dc47",
        "from": "one1uqaf0cnpe2vf9njse3ss6twx0plcg5qs38xqvh",
        "gas": 164166,
        "gasPrice": 10000000000,
        "hash": "0x50b2247d7ed2b3035ce53cffb4b431bdbd033b547b6e38df3f4c1a2d849ab5c5",
        "input": "0x96b5a755000000000000000000000000000000000000000000000000000000000000c8e9",
        "nonce": 1342,
        "r": "0x15949d64bda389068fef2ee8895c0bf9a9242a665b463c82c74e18b6058b014b",
        "s": "0x6c983bc15f25ed6e6836086a808f9ad6dc165df265201d56c3a75e30e522e4a2",
        "shardID": 0,
        "timestamp": 1640775968,
        "to": "one1zwn9h8uq883vqv4uqgshrhq9kvxr72yjjjz9la",
        "toShardID": 0,
        "transactionIndex": 39,
        "v": "0xc6ac98a3",
        "value": 0
    }
}
```
log from the blockchain is 
```
        {
            "address": "0x5f753dcdf9b1ad9aabc1346614d1f4746fd6ce5c",
            "topics": [
                "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                "0x00000000000000000000000013a65b9f8039e2c032bc022171dc05b30c3f2892",
                "0x000000000000000000000000e03a97e261ca9892ce50cc610d2dc6787f845010",
                "0x000000000000000000000000000000000000000000000000000000000000c8e9"
            ],
            "data": "0x",
            "blockNumber": "0x141ae92",
            "transactionHash": "0x50b2247d7ed2b3035ce53cffb4b431bdbd033b547b6e38df3f4c1a2d849ab5c5",
            "transactionIndex": "0x27",
            "blockHash": "0x0ada348ac4423b5158398cabc13cc729437d7e4e077dd50cd3c6a4c2f4789ae9",
            "logIndex": "0x84",
            "removed": false
        },
```

decoded logs seem inaccurate....

**Comment by ndhung1104** [comment]
The problem with this one is: it doesn't have a "value" field. Even though it's classified as a Transfer event, it only has from/to address + a field called token_id. 

Checking on the explorer:
![image](https://user-images.githubusercontent.com/96320869/149134592-f9d5c13c-0e36-4a41-b60d-d5c1af6d8c86.png)

The contract address 0x5F753dcDf9b1AD9AabC1346614D1f4746fd6Ce5C is the Hero contract address of DFK. So, I think this is a NFT transfer.

=>If there is no need, I will just remove this with a NULL filter on the value field.

**Comment by antonyip** [comment]
> The problem with this one is: it doesn't have a "value" field. Even though it's classified as a Transfer event, it only has from/to address + a field called token_id.
> 
> Checking on the explorer: ![image](https://user-images.githubusercontent.com/96320869/149134592-f9d5c13c-0e36-4a41-b60d-d5c1af6d8c86.png)
> 
> The contract address 0x5F753dcDf9b1AD9AabC1346614D1f4746fd6Ce5C is the Hero contract address of DFK. So, I think this is a NFT transfer.
> 
> =>If there is no need, I will just remove this with a NULL filter on the value field.

Ooh! didn't think about ERC-721 tokens... I guess the transfer event is exactly the same as ERC-20's.. 

Yup, I guess we can go with the NULL filter.
