### ISSUE TITLE
[Table] tranquil_repayments

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#53]
EDIT: I've just copied and pasted from a previous issue, might not be cleaned correctly.

| block_timestamp     | block_id | user_address | contract_address                           | token_address | token_amount_raw | token_amount | amount_usd |
|---------------------|----------|--------------|--------------------------------------------|---------------|------------------|--------------|------------|
| 2022-01-01 15:00:00 | 25001234 | 0x           | 0x34b9aa82d89ae04f0f546ca5ec9c93efe1288940 | 0x            | 1234567          | 1.234567     | 0.33       |

Hints:
<https://app.tranquil.finance/markets>

## Tranquil's Controller
0x6a82A17B48EF6be278BBC56138F35d04594587E3 

## Token addresses (Just click on the approval to see which contract you're giving the approval to)
ONE - 0x34B9aa82D89AE04f0f546Ca5eC9C93eFE1288940
stOne - 0x973f22036a0ff3a93654e7829444ec64cb37bd78
WBTC - 0xd9c0d8ad06abe10ab29655ff98dcaaa0e059184a
1BTC - 0x481721b918c698ff5f253c56684bac8dca84346c
1ETH - 0xc63ab8c72e636c9961c5e9288b697ec5f0b8e1f7
1USDC - ?
1USDT - ?
1DAI - ?

**Comment by davidenoch** [comment]
1USDC -0xca3e902efdb2a410c952fd3e4ac38d7dbdcb8e96
1USDT -0x7af2430efa179db0e76257e5208bcaf2407b2468
1DAI - 0x49d95736fe7f1f32e3ee5defc26c95ba22834639

(see my incredibly insightful comments to issue #50
