### ISSUE TITLE
Review Shared Tables

### ISSUE THREAD

**Issue by drakedanner** [MetricsDAO/harmony_dbt#67]
A consumer of our data (shared from MetricsDAO to Flipside) has noted that tokenprices are not up to date. @antonyip notes that the prices model should not be shared.

Can someone review the models exposed via the share and ensure that the proper tables are shared.

- [ ] Review tables in Flipside
- [ ] Prepare list of tables that should be shared
- [ ] Note for each table if it should be kept, removed, etc

**Comment by antonyip** [comment]
![image](https://user-images.githubusercontent.com/9086733/156264716-552ee4d9-3827-46fa-9e85-3e63db6e063f.png)

**Comment by chuxinh** [comment]
I'd say the following to be included

- [x] blocks 
- [x] logs
- [ ] btc_bridge
- [x] liquidity_pools
- [x] swaps
- [x] tokens
- [x] transfers
- [x] txs

- [ ] tranquil_daily_supply_borrow
- [ ] tranquil_daily_markets_token_price
- [ ] tranquil_market_labels
- [ ] tranquil_txs

- [ ] metric_*

**Comment by antonyip** [comment]
@chuxinh Reasons for `btc_bridge` and `tranquil_txs` to be taken out?
I'm fine with exposing these 2 as they're just filtered from txs + logs.
How about the dfk_* tables?

**Comment by chuxinh** [comment]
> @chuxinh Reasons for `btc_bridge` and `tranquil_txs` to be taken out? I'm fine with exposing these 2 as they're just filtered from txs + logs. How about the dfk_* tables?

oh, not meaning it's taken out, but saying they should be included but not exist in the flipside yet. I'll defer to u for all the dfk_*
