### ISSUE TITLE
[Table] Validators

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#73]
**Description**
Let's create a table using `harmony.dev.stg_validators` as the source data table.
The idea behind this is to expose validator data to Flipside's Velocity.

Additional Questions you can ask yourself:
  - What is inside the source data table that is important to be exposed for the public to use?
  - Is there anything else that I wish to have for this table that does not exists yet?
  - How will I use this data for analysis?

**To Do Next:**

- [ ] Design the schema for this table
- [ ] Get confirmation on schema
- [ ] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request

**Comment by eevui** [comment]
I'd like to take this issue, if that's all right.

**Comment by antonyip** [comment]
Go for it! @eevui

**Comment by eevui** [comment]
Thanks.

First look at the table on snowflake, there's... barely anything in it! I'm not entirely sure how this would be a useful table, to be quite honest. 

On checking similar tables available on Flipside---Terra, for instance, I believe some interesting data to expose would be the validator's identity and their voting power. This data could be found at `stg_delegators` instead.

Thus, I propose the following schema with sample data:

| timestamp               | validator_address                          | validator_identity | active_status | booted_status                                   | voting_power          |
|-------------------------|--------------------------------------------|--------------------|---------------|-------------------------------------------------|-----------------------|
| 2022-03-20 09:32:02.611 | one1jsgnppqzam8dqh305hlehuvzsc5lvw55qp848z | HarmonicValidator1 | inactive      | manually turned inactive or insufficient uptime | 0                     |
| 2022-03-20 09:32:02.611 | one1ksqcladc3r5s90v494h9tfwdhkx88tq6j549f6 | Staking-Power      | active        | NULL                                            | 1.000100000000000e+22 |

Voting power here only refers to the validator's staked ONE and not including the ONE delegated to them.

If one were to be curious of the number of active validators, one can easily query for validators with `active_status = 'active'` and can be grouped by `timestamp`.

I'm not sure of the scope of the `validators` table, but the `stg_delegators` table still has a column for total ONE staked, and the number of delegators under them. This could be added as well, but perhaps considering we'll have a separate delegators table, that sort of information can be queried out from there instead.

**Comment by antonyip** [comment]
Hey @eevui,

Great Start! My bad for not double checking the stg_validator tables.

Went to take a look at the stg_validators.. yep, there's not much.. I'm okay to pull data from stg_delegators too if you want to join them. Couple of interesting things that you may consider.

- Lets try to have an hourly or daily average of how much is ( staked / number of address staking / how much undelegating / how much does the validator owe delegators)
- There's a user-defined function called js_onetohex that will convert one addresses to hexaddresses. lets use that and create another column that shows the validator_address in hex.
![image](https://user-images.githubusercontent.com/9086733/159165040-79752009-a098-4ec8-b6b9-74ab57d9a463.png)

Delegator Table will have an angle that will show information from the point of the addresses of the delegators so what you're trying to populate will look different.

Let me know if you have any concerns!

**Comment by eevui** [comment]
I was thinking of not pulling from stg_validators at all.

> Lets try to have an hourly or daily average of how much is ( staked / number of address staking / how much undelegating / how much does the validator owe delegators)

As for the number of delegators per validator, I believe we can pull that value from joining with the future delegators table. Or would it be handy in this table too? Of course I defer to you fellas.

As for the hourly or daily average, as far as I can tell, the ingest occurs not hourly, so perhaps a daily tally would be better. We can group by `day_date` instead of the `ingest_timestamp`. I'm considering taking the latest row of the day instead of taking an average? I think an average would give a wrong idea of the data.

As for the other values such as ONE staked, undelegated, I take it we show the totals here only? So total ONE delegated and total ONE undelegated for that day?

> There's a user-defined function called js_onetohex that will convert one addresses to hexaddresses. lets use that and create another column that shows the validator_address in hex.

Sure, can add that column to the schema as `validator_hex_address`.

**Comment by eevui** [comment]
On closer look, on average there are around 13 ingest points per day for each validator. With a mode of 4 ingests a day. Sounds a bit low to consider an hourly statistic.

**Comment by antonyip** [comment]
1. Number of Delegators should be in this table, it'll be a stat that's relevant for the validators.
2. Daily's fine... Latest row of the day is fine too..
3. Yup, totals.

Just FYI i guess, I'm imagining the delegator table to be like 
[day_date, delegator_address, total_amount_staked, total_amount_unbonding]
which is similar to what you have, but from the delegators direction.

**Comment by eevui** [comment]
> 1. Number of Delegators should be in this table, it'll be a stat that's relevant for the validators.

Sure, can add that to the schema.

Then can also add `total_one_delegated`, `total_one_undelegated`, and `total_one_rewarded`.

I'll build a query and try to get result that matches this schema.

**Comment by eevui** [comment]
Here's the first 100 rows I got from Snowflake with the SQL I created, hope it looks right! [validators.csv](https://github.com/MetricsDAO/harmony_dbt/files/8324952/validators.csv)

If all's well, I can port it to DBT.

**Comment by antonyip** [comment]
Looks good!

**Comment by antonyip** [comment]
Completed
