### ISSUE TITLE
[Table] Delegators

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#74]
**Description**
Let's create a table using `harmony.dev.stg_delegators` as the source data table.
The idea behind this is to expose delegator data to Flipside's Velocity.

Additional Questions you can ask yourself:
  - What is inside the source data table that is important to be exposed for the public to use?
  - Is there anything else that I wish to have for this table that does not exists yet?
  - How will I use this data for analysis?

**To Do Next:**

- [ ] Design the schema for this table
- [ ] Get confirmation on schema
- [ ] Build schema
- [ ] Schema build review
- [ ] Submit Pull Request

**Comment by covendev** [comment]
would be interested to work on this task. Can you please redirect me to the link that points to harmony.dev.stg_delegators and other related data  linked to it that is presently available

**Comment by geewynn** [comment]
Proposed schema

| day_date | delegator_address  | total_amount_delegated | total_amount_undelegated | delegator_reward |
|----------|-------------------------|--------------------------------------------------------------------|--------------------------------------------------------------------|-----------|
| 2022-02-20 00:00:00.000  |"one1fg5vsk0gy0jd2nf6m68zg7cxukcnsqwpncxaj0" | 0 | 9.6e+21|  1.24611807796064e+18 |

cc: @forgxyz @antonyip @chuxinh please let me know if this looks good.
reference: 
1. https://docs.harmony.one/home/developers/api/methods/staking-related-methods/hmy_getdelegationsbyvalidator
2. https://docs.harmony.one/home/developers/api/methods/staking-related-methods/hmy_getdelegationsbydelegatorandvalidator
3. https://docs.harmony.one/home/developers/api/methods/staking-related-methods/hmy_getdelegationsbydelegator

**Comment by antonyip** [comment]
@geewynn Heya,
Might wanna reference this for notes :) https://github.com/MetricsDAO/harmony_dbt/issues/73#issuecomment-1073254439

**Comment by geewynn** [comment]
Hey @antonyip I have gone through the reply and was wondering if there's anything in particular you think can be added to the model above.

I am also thinking if I should remove the validator_address, validatos_address_hex from the model and only focus on the data relevants to the delegators.

Columns can be `day_date`, `delegator_address`, `total_amount_delegated`, `total_amount_undelegated`, `delegator_reward`

How do you feel about this?

**Comment by antonyip** [comment]
yup, sounds good.
