### ISSUE TITLE
Feature: Add creator address to liquidity pool table

### ISSUE THREAD

**Issue by tonykau1** [MetricsDAO/harmony_dbt#84]
This, in combination with some labeling, could help identify volume/pairs by DEX and lead to some interesting Q&A.  

Suggested by @mufasa on #active-projects

**Comment by eevui** [comment]
I can take this.

**Comment by eevui** [comment]
Perhaps the table should be renamed to... liquidity providers and not pool.

Also, some of these logs aren't filled yet so they're missing creator address.

Here's the first 100 rows I got from updating the existing model. 
[creator address lp.csv](https://github.com/MetricsDAO/harmony_dbt/files/8832997/creator.address.lp.csv)

**Comment by eevui** [comment]
@antonyip does this look good? I can submit a PR later.

**Comment by antonyip** [comment]
> @antonyip does this look good? I can submit a PR later.

yea looks good
