### ISSUE TITLE
Bug with missing token addresses

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#97]
Swaps are missing token addresses
```
select token0_address, count(1)
from MDAO_HARMONY.SWAPS
group by 1
order by 2 desc
```

**Comment by Vahid-flipside** [comment]
I looked at your model for the swap table. There must be a problem with the join because the liquidity_pool table already has those token addresses. And their relative pool addresses also exist in the logs table.

**Comment by antonyip** [comment]
Did a full-refresh on the table, we had changes that was not propagated to the production servers.
